from classes import Tuile

#V pour ville, P pour prairie, R pour route
tuile1 = Tuile("P","P","P","P")
tuile2 = Tuile("P","P","P","P")
tuile3 = Tuile("P","P","P","P")
tuile4 = Tuile("P","P","P","P")
tuile5 = Tuile("P","P","P","V")
tuile6 = Tuile("P","P","R","P")
tuile7 = Tuile("P","P","R","P")
tuile8 = Tuile("P","P","R","R")
tuile9 = Tuile("P","P","R","R")
tuile10 = Tuile("P","R","P","R")
tuile11 = Tuile("P","R","P","R")
tuile12 = Tuile("P","R","P","R")
tuile13 = Tuile("P","R","P","R")
tuile14 = Tuile("P","R","P","R")
tuile15 = Tuile("P","R","P","R")
tuile16 = Tuile("P","R","P","R")
tuile17 = Tuile("P","R","R","P")
tuile18 = Tuile("P","R","R","P")
tuile19 = Tuile("P","R","R","R")
tuile20 = Tuile("P","R","R","V")
tuile21 = Tuile("P","R","R","V")
tuile22 = Tuile("P","R","V","R")
tuile23 = Tuile("P","V","P","P")
tuile24 = Tuile("P","V","R","R")
tuile25 = Tuile("P","V","R","R")
tuile26 = Tuile("P","V","R","R")
tuile27 = Tuile("P","V","V","V")
tuile28 = Tuile("R","P","P","R")
tuile29 = Tuile("R","P","P","R")
tuile30 = Tuile("R","P","P","R")
tuile31 = Tuile("R","P","P","V")
tuile32 = Tuile("R","P","R","P")
tuile33 = Tuile("R","P","R","R")
tuile34 = Tuile("R","P","R","V")
tuile35 = Tuile("R","R","P","P")
tuile36 = Tuile("R","R","P","P")
tuile37 = Tuile("R","R","P","P")
tuile38 = Tuile("R","R","P","R")
tuile39 = Tuile("R","R","P","V")
tuile40 = Tuile("R","R","R","R")
tuile41 = Tuile("R","R","R","R")
tuile42 = Tuile("R","R","R","V")
tuile43 = Tuile("R","R","V","P")
tuile44 = Tuile("R","R","V","P")
tuile45 = Tuile("R","R","V","R")
tuile46 = Tuile("R","R","V","V")
tuile47 = Tuile("R","V","R","P")
tuile48 = Tuile("R","V","R","R")
tuile49 = Tuile("R","V","V","P")
tuile50 = Tuile("R","V","V","R")
tuile51 = Tuile("R","V","V","R")
tuile52 = Tuile("R","V","V","V")
tuile53 = Tuile("R","V","V","V")
tuile54 = Tuile("V","P","P","P")
tuile55 = Tuile("V","P","P","V")
tuile56 = Tuile("V","P","P","V")
tuile57 = Tuile("V","P","V","P")
tuile58 = Tuile("V","P","V","R")
tuile59 = Tuile("V","R","P","R")
tuile60 = Tuile("V","R","R","V")
tuile61 = Tuile("V","R","R","V")
tuile62 = Tuile("V","R","V","R")
tuile63 = Tuile("V","V","P","P")
tuile64 = Tuile("V","V","P","P")
tuile65 = Tuile("V","V","P","V")
tuile66 = Tuile("V","V","P","V")
tuile67 = Tuile("V","V","R","V")
tuile68 = Tuile("V","V","R","V")
tuile69 = Tuile("V","V","R","V")
tuile70 = Tuile("V","V","V","P")
tuile71 = Tuile("V","V","V","P")
tuile72 = Tuile("V","V","V","V")

pioche = [
    tuile1, tuile2, tuile3, tuile4, tuile5, tuile6, tuile7, tuile8, tuile9, tuile10,
    tuile11, tuile12, tuile13, tuile14, tuile15, tuile16, tuile17, tuile18, tuile19, tuile20,
    tuile21, tuile22, tuile23, tuile24, tuile25, tuile26, tuile27, tuile28, tuile29, tuile30,
    tuile31, tuile32, tuile33, tuile34, tuile35, tuile36, tuile37, tuile38, tuile39, tuile40,
    tuile41, tuile42, tuile43, tuile44, tuile45, tuile46, tuile47, tuile48, tuile49, tuile50,
    tuile51, tuile52, tuile53, tuile54, tuile55, tuile56, tuile57, tuile58, tuile59, tuile60,
    tuile61, tuile62, tuile63, tuile64, tuile65, tuile66, tuile67, tuile68, tuile69, tuile70,
    tuile71, tuile72
]